name: "Export Web"

on:
  workflow_call:
    inputs:
      templates_cache_key:
        required: true
        type: string
      deploy_version:
        required: true
        type: string

permissions:
  contents: read

jobs:
  export-web:
    name: Build & Deploy
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:${{ vars.GODOT_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Prepare Export Caches
        uses: ./.github/actions/prepare-export-caches
        with:
          project_path: ${{ vars.PROJECT_PATH }}
          godot_version: ${{ vars.GODOT_VERSION }}
          templates_cache_key: ${{ inputs.templates_cache_key }}

      - name: Web Build
        uses: ./.github/actions/run-godot-export
        with:
          project_path: ${{ vars.PROJECT_PATH }}
          godot_version: ${{ vars.GODOT_VERSION }}
          godot_version_label: ${{ vars.GODOT_VERSION_LABEL }}
          export_preset: Web
          output_subpath: web/index.html

      - name: Deploy Web to itch.io
        uses: ./.github/actions/deploy-butler
        with:
          source_path: build/web
          channel: ${{ vars.ITCHIO_CHANNEL }}:web
          deploy_version: ${{ inputs.deploy_version }}
          butler_api_key: ${{ secrets.BUTLER_API_KEY }}
