name: "Export Windows"

on:
  workflow_call:
    inputs:
      templates_cache_key:
        required: true
        type: string
      deploy_version:
        required: true
        type: string

permissions:
  contents: read

jobs:
  export-windows:
    name: Build & Deploy
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:${{ vars.GODOT_VERSION }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - name: x86_64
            export_preset: Windows - x86_64
            output_subpath: windows/x86_64/${{ vars.PROJECT_NAME }}_win_x86_64.exe
            channel_suffix: win-x86_64
          - name: arm64
            export_preset: Windows - arm64
            output_subpath: windows/arm64/${{ vars.PROJECT_NAME }}_win_arm64.exe
            channel_suffix: win-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Prepare Export Caches
        uses: ./.github/actions/prepare-export-caches
        with:
          project_path: ${{ vars.PROJECT_PATH }}
          godot_version: ${{ vars.GODOT_VERSION }}
          templates_cache_key: ${{ inputs.templates_cache_key }}

      - name: Build Windows ${{ matrix.target.name }}
        uses: ./.github/actions/run-godot-export
        with:
          project_path: ${{ vars.PROJECT_PATH }}
          godot_version: ${{ vars.GODOT_VERSION }}
          godot_version_label: ${{ vars.GODOT_VERSION_LABEL }}
          export_preset: ${{ matrix.target.export_preset }}
          output_subpath: ${{ matrix.target.output_subpath }}

      - name: Deploy Windows ${{ matrix.target.name }} to itch.io
        uses: ./.github/actions/deploy-butler
        with:
          source_path: build/${{ matrix.target.output_subpath }}
          channel: ${{ format('{0}:{1}', vars.ITCHIO_CHANNEL, matrix.target.channel_suffix) }}
          deploy_version: ${{ inputs.deploy_version }}
          butler_api_key: ${{ secrets.BUTLER_API_KEY }}
