name: "Export Linux"

on:
  workflow_call:
    inputs:
      templates_cache_key:
        required: true
        type: string
      deploy_version:
        required: true
        type: string

permissions:
  contents: read

jobs:
  export-linux:
    name: Build & Deploy
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:${{ vars.GODOT_VERSION }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - name: x86_64
            export_preset: Linux - x86_64
            output_subpath: linux/x86_64/${{ vars.PROJECT_NAME }}.x86_64
            channel_suffix: linux-x86_64
          - name: arm64
            export_preset: Linux - arm64
            output_subpath: linux/arm64/${{ vars.PROJECT_NAME }}.arm64
            channel_suffix: linux-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Prepare Export Caches
        uses: ./.github/actions/prepare-export-caches
        with:
          project_path: ${{ vars.PROJECT_PATH }}
          godot_version: ${{ vars.GODOT_VERSION }}
          templates_cache_key: ${{ inputs.templates_cache_key }}

      - name: Build Linux ${{ matrix.target.name }}
        uses: ./.github/actions/run-godot-export
        with:
          project_path: ${{ vars.PROJECT_PATH }}
          godot_version: ${{ vars.GODOT_VERSION }}
          godot_version_label: ${{ vars.GODOT_VERSION_LABEL }}
          export_preset: ${{ matrix.target.export_preset }}
          output_subpath: ${{ matrix.target.output_subpath }}

      - name: Deploy Linux ${{ matrix.target.name }} to itch.io
        uses: ./.github/actions/deploy-butler
        with:
          source_path: build/${{ matrix.target.output_subpath }}
          channel: ${{ format('{0}:{1}', vars.ITCHIO_CHANNEL, matrix.target.channel_suffix) }}
          deploy_version: ${{ inputs.deploy_version }}
          butler_api_key: ${{ secrets.BUTLER_API_KEY }}
