name: "Export Android"

on:
  workflow_call:
    inputs:
      templates_cache_key:
        required: true
        type: string
      deploy_version:
        required: true
        type: string

permissions:
  contents: read

jobs:
  export-android:
    name: Build & Deploy
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:${{ vars.GODOT_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Prepare Export Caches
        uses: ./.github/actions/prepare-export-caches
        with:
          project_path: ${{ vars.PROJECT_PATH }}
          godot_version: ${{ vars.GODOT_VERSION }}
          templates_cache_key: ${{ inputs.templates_cache_key }}
          templates_restore_keys: |
            godot-templates-${{ vars.GODOT_VERSION }}-
            godot-templates-

      - name: Prepare Android
        uses: ./.github/actions/prepare-android
        with:
          godot_version: ${{ vars.GODOT_VERSION }}
          godot_version_label: ${{ vars.GODOT_VERSION_LABEL }}

      - name: Android APK Build
        env:
          GODOT_ANDROID_KEYSTORE_RELEASE_PATH: ${{ github.workspace }}/export/keystore/quintessence_maven.jks
          GODOT_ANDROID_KEYSTORE_RELEASE_USER: quintessence
          GODOT_ANDROID_KEYSTORE_RELEASE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASS }}
        uses: ./.github/actions/run-godot-export
        with:
          project_path: ${{ vars.PROJECT_PATH }}
          godot_version: ${{ vars.GODOT_VERSION }}
          godot_version_label: ${{ vars.GODOT_VERSION_LABEL }}
          export_preset: Android - APK
          output_subpath: android/${{ vars.PROJECT_NAME }}.apk

      - name: Deploy Android APK to itch.io
        continue-on-error: true
        uses: ./.github/actions/deploy-butler
        with:
          source_path: build/android/${{ vars.PROJECT_NAME }}.apk
          channel: ${{ vars.ITCHIO_CHANNEL }}:android-apk
          deploy_version: ${{ inputs.deploy_version }}
          butler_api_key: ${{ secrets.BUTLER_API_KEY }}
          allow_missing: "true"
