name: gdunit4 tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gdunit4:
    name: Run GDUnit4 Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Run GDUnit4 tests
        uses: godot-gdunit-labs/gdUnit4-action@v1.3.0
        with:
          godot-version: "4.6.1"
          paths: "res://tests"
          timeout: 15
          publish-report: false
          upload-report: false
          report-name: gdunit4-test-report.xml
