name: "Continuous Integration"

on:
  workflow_dispatch:
    inputs:
      build_web:
        description: "Build Web export"
        required: false
        default: true
        type: boolean
      build_windows:
        description: "Build Windows exports"
        required: false
        default: true
        type: boolean
      build_linux:
        description: "Build Linux exports"
        required: false
        default: true
        type: boolean
      build_android:
        description: "Build Android exports"
        required: false
        default: false
        type: boolean
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-checks:
    name: Verify Unit Tests and Static Checks
    uses: ./.github/workflows/static-checks.yml

  setup-templates:
    name: Setup Templates
    needs: static-checks
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:${{ vars.GODOT_VERSION }}
    outputs:
      godot-version: ${{ vars.GODOT_VERSION }}
      godot-version-label: ${{ vars.GODOT_VERSION_LABEL }}
      templates-cache-key: ${{ steps.setup.outputs.templates_cache_key }}
      deploy-version: ${{ steps.setup.outputs.deploy_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup Templates Metadata and Cache
        id: setup
        uses: ./.github/actions/setup-templates
        with:
          godot_version: ${{ vars.GODOT_VERSION }}
          godot_version_label: ${{ vars.GODOT_VERSION_LABEL }}

  export-windows:
    name: Windows Export
    if: ${{ inputs.build_windows != 'false' }}
    needs: setup-templates
    uses: ./.github/workflows/export-windows.yml
    with:
      templates_cache_key: ${{ needs.setup-templates.outputs.templates-cache-key }}
      deploy_version: ${{ needs.setup-templates.outputs.deploy-version }}
    secrets: inherit

  export-linux:
    name: Linux Export
    if: ${{ inputs.build_linux != 'false' }}
    needs: setup-templates
    uses: ./.github/workflows/export-linux.yml
    with:
      templates_cache_key: ${{ needs.setup-templates.outputs.templates-cache-key }}
      deploy_version: ${{ needs.setup-templates.outputs.deploy-version }}
    secrets: inherit

  export-web:
    name: Web Export
    if: ${{ inputs.build_web != 'false' }}
    needs: setup-templates
    uses: ./.github/workflows/export-web.yml
    with:
      templates_cache_key: ${{ needs.setup-templates.outputs.templates-cache-key }}
      deploy_version: ${{ needs.setup-templates.outputs.deploy-version }}
    secrets: inherit

  export-android:
    name: Android Export
    if: ${{ inputs.build_android == 'true' }}
    needs: setup-templates
    uses: ./.github/workflows/export-android.yml
    with:
      templates_cache_key: ${{ needs.setup-templates.outputs.templates-cache-key }}
      deploy_version: ${{ needs.setup-templates.outputs.deploy-version }}
    secrets: inherit
